# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

version: 2
project_name: params2env

builds:
  - main: .
    binary: params2env
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.version={{ .Version }}" -X "main.commit={{ .FullCommit }}" -X "main.date={{ .Date }}"

archives:
  - formats: [tar.gz]
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - CHANGELOG.md
      - CHANGELOG.md.license
      - LICENSES/*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  use: git
  abbrev: 8
  groups:
    - title: "Features"
      regexp: '^feat:'
      order: 0
    - title: "Bug Fixes"
      regexp: '^fix:'
      order: 1
    - title: "Build"
      regexp: '^build:'
      order: 2
    - title: "Test"
      regexp: '^tests?:'
      order: 3
    - title: "Bump"
      regexp: '^bump:'
      order: 4
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
      - "^refactor:"

release:
  github:
    owner: wombelix
    name: params2env
