# SPDX-FileCopyrightText: 2025 Dominik Wombacher <dominik@wombacher.cc>
#
# SPDX-License-Identifier: MIT

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/golangci/golangci-lint
    rev: v2.3.1
    hooks:
    -   id: golangci-lint
    -   id: golangci-lint-config-verify
-   repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
    -   id: markdownlint_docker
        exclude: CHANGELOG.md
-   repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
    -   id: reuse
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.3
    hooks:
    -   id: commitizen
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    -   id: shellcheck
        args:
          - -x
